sudo: required

language: c

services:
- docker

env:
  global:
    - INSTALL_ROOT=/tool-chains
    - BUILD_ROOT=/tmp
    - BUILD=build
  matrix:
    - OPTION_DEV_CARTRIDGE=0 BUILD_TYPE=release
    - OPTION_DEV_CARTRIDGE=0 BUILD_TYPE=debug

    - OPTION_DEV_CARTRIDGE=1 BUILD_TYPE=release
    - OPTION_DEV_CARTRIDGE=1 BUILD_TYPE=debug

    - OPTION_DEV_CARTRIDGE=2 BUILD_TYPE=release
    - OPTION_DEV_CARTRIDGE=2 BUILD_TYPE=debug

    - OPTION_DEV_CARTRIDGE=0 BUILD_TYPE=tools
    - OPTION_DEV_CARTRIDGE=1 BUILD_TYPE=tools
    - OPTION_DEV_CARTRIDGE=2 BUILD_TYPE=tools

before_script:
- docker pull ijacquez/libyaul-tool-chain:1.2

script:
- docker run --name "container" -e "TRAVIS_BRANCH=${TRAVIS_BRANCH}" -e "BUILD_TYPE=${BUILD_TYPE}" -e "INSTALL_ROOT=${INSTALL_ROOT}"  -e "BUILD_ROOT=${BUILD_ROOT}" -e "BUILD=${BUILD}" -e "OPTION_DEV_CARTRIDGE=${OPTION_DEV_CARTRIDGE}" -w /tmp -t -d ijacquez/libyaul-tool-chain:1.2 sh
- docker cp .ci-build.sh container:/tmp/.ci-build.sh
- docker exec container sh -e /tmp/.ci-build.sh
